name: countdown
description: countdown.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http_client_hoc081098: ^0.1.0
  http: ^1.0.0
  rxdart_ext: ^0.3.0

dev_dependencies:
  lints: ^2.1.1
