name: countdown
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '<4.0.0'

dependencies:
  http_client_hoc081098: ^0.0.1-dev.0
  http: ^0.13.5
  rxdart_ext: ^0.2.7

dev_dependencies:
  lints: ^2.0.1

