name: countdown
description: countdown.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http_client_hoc081098: ^0.1.0
  http: ^0.13.5
  rxdart_ext: ^0.2.9

dev_dependencies:
  lints: ^2.1.1

dependency_overrides:
  http_client_hoc081098:
    git:
      url: https://github.com/hoc081098/http_client_hoc081098.git
      ref: 92b5155b6ea76bb0ecf98179bf9404d3dfffb2b3