name: Count down

on:
  schedule:
   - cron: '0 3 * * 1' # Runs at 03:00, only on Monday.
  workflow_dispatch:

env:
  CI: true

jobs:
  random-quote:
    if: ${{ github.repository == 'hoc081098/hoc081098' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./countdown

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Print Dart version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Run
        run: dart run lib/main.dart
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
