name: Grid snake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 */6 * * *' # Runs on the 0, 6, 12 and 18th hour.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: hoc081098
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Pull
        run: git pull origin master

      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: "[Grid snake] Update action output"
          file_pattern: 'dist/*.svg'
          commit_user_name: hoc081098
          commit_user_email: hoc081098@gmail.com # defaults to "github-actions[bot]@users.noreply.github.com"
          commit_author: Petrus Nguyễn Thái Học <hoc081098@gmail.com> # defaults to author of the commit that triggered the run
