name: Grid snake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:
    - cron: '0 */2 * * *' # Runs on the 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 and 22nd hour.

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: hoc081098
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Pull
        run: git pull origin master

      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: "[Grid snake] Update action output"
          file_pattern: dist/github-contribution-grid-snake.svg
          commit_user_name: hoc081098
          commit_user_email: hoc081098@gmail.com # defaults to "github-actions[bot]@users.noreply.github.com"
          commit_author: Petrus Nguyễn Thái Học <hoc081098@gmail.com> # defaults to author of the commit that triggered the run
